project:
  type: website
  output-dir: docs

website:
  title: "KV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sql.qmd
        text: SQL

format:
  html:
    theme: flatly
    css: styles.css
    toc: true