project:
  type: website
  output-dir: docs

website:
  title: "KV"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "SQL"
        menu:
          - href: sql.qmd
          - text: SQL Gala darbs
      - text: "R"
        menu:
          - href: R-MD4.qmd
          - text: MD 4
 
format:
  html:
    theme: flatly
    css: styles.css
    toc: true