---
title: "R Language Exam"
---

# Big Tech Stock Prices

## 1. Izmantotās bibliotēkas

```{r}
#| warning: false
#| error: false
#| echo: false

# Bibliotēku ielāde ####

# tidayverse datu pakotne
library(tidyverse)
# datu iepazīšanās pakotne
library(skimr)

```

## 2. Datu ielāde

```{r}
#| warning: false
#| error: false
#| echo: false
# ielādējam datu objektu
tuesdata <- tidytuesdayR::tt_load('2023-02-07')
# sadalām objektu pa datuframe
prices <- tuesdata$big_tech_stock_prices 
companies <- tuesdata$big_tech_companies
```

## 3. Veicam sākotnējo datu analīzi un izpētam pieejamos datus

```{r}
#| warning: false
#| error: false
#| echo: false
# Datu analīze ####
# summary statistics
skim(prices)
skim(companies)

```

Nelielas tabulas, tīras, nav trūksošo datu, tabula companies ir samērā maza, nepieciešams to apvienot ar pamat prices tabulu

```{r}
## Tabulu apvienošana ####
data <- prices %>% 
  left_join(companies, by = "stock_symbol")
## Tabulu datu tipu pārveidošana ####
data %>% 
  mutate(
    # definēja, ka date ir pareizā datu formāta
    date = as.Date(date, format = "%Y%m%d"),
    # pārveidojam nominālos mainīgos par faktoriem
    stock_symbol = as.factor(stock_symbol),
    company = as.factor(company)
  ) %>% 
    # pārsaucam tabulas kolonu
  rename(
    "stock" = "stock_symbol"
  ) %>% 
  glimpse()
 
```
